version: "3.3"

services:    

  elasticsearch:
    image: elasticsearch:7.9.3
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    volumes:
      - esdata:/usr/share/elasticsearch/data


  kibana:
    image: kibana:7.9.3
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"


  logstash:
    image: logstash:7.9.3
    ports:
      - "12201:12201/udp"
    depends_on:
      - elasticsearch
    deploy:
      mode: global
    configs:
      - source: logstash_conf
        target: /usr/share/logstash/pipeline/logstash.conf
    volumes:
      - logstash-pipeline:/usr/share/logstash/pipeline/


  zipkin-service:
      image: openzipkin/zipkin
      # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
      ports:
        - 9411:9411
      depends_on:
        - elasticsearch
        
configs:
  logstash_conf:
    file: ./logstash.conf

volumes:
  esdata:
    driver: local
  logstash-pipeline:
    driver: local